### ISSUE TITLE
Wrong exception when using a validation rule that does not exist.

### ISSUE THREAD

**Issue by nuvalis** [mosbth/cform#11]
This is what I get when using a rule that does not exist ->

Fatal error: Class 'Mos\HTMLForm\Exception' not found in /var/www/kmom4/vendor/mos/cform/src/HTMLForm/CFormElement.php on line 351

Looks like the Exception class is not in the right namespace. Expected error and namespace should be like below.

```
// CFormElement.php line 350
if (!isset($tests[$rule])) {
    throw new \Exception("Validation of form element failed, no such validation rule exists: $rule");
}

I changed Exception() to \Exception() and it should now work.
```

**Comment by mosbth** [comment]
Yepp, wrong namespace for exception. Corrected and included a testcase for it.

Related to branch v2, corrected in latest.
